#include <stdio.h>
#include <conio.h>
void main()
{
int a, b, c, menor;
printf("Digite um n£mero: %d",a);
scanf("%d",&a);
printf("Digite outro n£mero: %d",b);
scanf("%d",&b);
printf("Digite outro n£mero: %d",c);
scanf("%d",&c);
  if (a<b && a<c)
	printf("O menor n£mero ‚: %d",a);
  else if (b<c)
	printf("O menor n£mero ‚: %d",b);
	else
	 printf("O menor n£mero ‚: %d",c);
getche();
}