#include <stdio.h>
#include <conio.h>
void main()
{
int n1, n2, n3, n4, n5, n6, soma;
printf("Digite o 1o n£mero: %d",n1);
scanf("%d",&n1);
printf("Digite o 2o n£mero: %d",n2);
scanf("%d",&n2);
printf("Digite o 3o n£mero: %d",n3);
scanf("%d",&n3);
printf("Digite o 4o n£mero: %d",n4);
scanf("%d",&n4);
printf("Digite o 5o n£mero: %d",n5);
scanf("%d",&n5);
printf("Digite o 6o n£mero: %d",n6);
scanf("%d",&n6);
soma=n1+n2+n3+n4+n5+n6;
printf("A soma dos n£meros ‚: %d",soma);
scanf("%d",&soma);
getche();
}