#include <stdio.h>
#include <conio.h>
void main()
{
clrscr();
printf("Os alunos s∆o %2d. \n",350);
printf("Os alunos s∆o %4d. \n",350);
printf("Os alunos s∆o %6d. \n \n",350);
printf("%4.2f \n",3456.78);
printf("%3.2f \n",3456.78);
printf("%3.1f \n",3456.78);
printf("%f \n",123.456789);
printf("%3.2f \n",123.456789);
printf("%e \n",123.456789);
printf("%13.2e \n",123.456789);
getche();
}
